// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ogma.Infrastructure.Persistence.Partners.Contexts;

#nullable disable

namespace Ogma.Infrastructure.Persistence.Partners.Migrations
{
    [DbContext(typeof(PartnersDbContext))]
    [Migration("20251209164241_FixHQAddressType")]
    partial class FixHQAddressType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("Relational:MigrationHistoryTable", "__PartnersMigrationsHistory");

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ogma.Infrastructure.Persistence.Partners.Models.Partner", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CompanyName")
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("IndividualFirstName")
                        .HasColumnType("text")
                        .HasColumnName("individual_first_name");

                    b.Property<string>("IndividualLastName")
                        .HasColumnType("text")
                        .HasColumnName("individual_last_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsNaturalPerson")
                        .HasColumnType("boolean")
                        .HasColumnName("is_natural_person");

                    b.HasKey("Id")
                        .HasName("pk_partners");

                    b.ToTable("partners", (string)null);
                });

            modelBuilder.Entity("Ogma.Infrastructure.Persistence.Partners.Models.PartnerContact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("JobTitle")
                        .HasColumnType("text")
                        .HasColumnName("job_title");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Mobile")
                        .HasColumnType("text")
                        .HasColumnName("mobile");

                    b.Property<long>("PartnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("partner_id");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_partner_contact");

                    b.HasIndex("PartnerId")
                        .HasDatabaseName("ix_partner_contact_partner_id");

                    b.ToTable("partner_contact", (string)null);
                });

            modelBuilder.Entity("Ogma.Infrastructure.Persistence.Partners.Models.PartnerIdentifier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<long>("PartnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("partner_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime?>("ValidityEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validity_end");

                    b.Property<DateTime>("ValidityStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validity_start");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_partner_identifier");

                    b.HasIndex("PartnerId")
                        .HasDatabaseName("ix_partner_identifier_partner_id");

                    b.ToTable("partner_identifier", (string)null);
                });

            modelBuilder.Entity("Ogma.Infrastructure.Persistence.Partners.Models.PartnerRoleType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_partner_role_types");

                    b.ToTable("partner_role_types", (string)null);
                });

            modelBuilder.Entity("PartnerPartnerRoleType", b =>
                {
                    b.Property<long>("PartnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("partner_id");

                    b.Property<long>("RolesId")
                        .HasColumnType("bigint")
                        .HasColumnName("roles_id");

                    b.HasKey("PartnerId", "RolesId")
                        .HasName("pk_partner_roles");

                    b.HasIndex("RolesId")
                        .HasDatabaseName("ix_partner_roles_roles_id");

                    b.ToTable("partner_roles", (string)null);
                });

            modelBuilder.Entity("Ogma.Infrastructure.Persistence.Partners.Models.Partner", b =>
                {
                    b.OwnsMany("Ogma.Infrastructure.Persistence.Partners.Models.PartnerBankAccount", "BankAccounts", b1 =>
                        {
                            b1.Property<long>("PartnerId")
                                .HasColumnType("bigint")
                                .HasColumnName("partner_id");

                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<long>("Id"));

                            b1.Property<bool>("IsDefault")
                                .HasColumnType("boolean")
                                .HasColumnName("is_default");

                            b1.HasKey("PartnerId", "Id")
                                .HasName("pk_partner_bank_accounts");

                            b1.ToTable("partner_bank_accounts", (string)null);

                            b1.WithOwner("Partner")
                                .HasForeignKey("PartnerId")
                                .HasConstraintName("fk_partner_bank_accounts_partners_partner_id");

                            b1.OwnsOne("Ogma.Infrastructure.Persistence.Partners.ValueObjectRecords.BankAccountRecord", "BankAccount", b2 =>
                                {
                                    b2.Property<long>("PartnerBankAccountPartnerId")
                                        .HasColumnType("bigint")
                                        .HasColumnName("partner_id");

                                    b2.Property<long>("PartnerBankAccountId")
                                        .HasColumnType("bigint")
                                        .HasColumnName("id");

                                    b2.Property<string>("Bank")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("bank");

                                    b2.Property<string>("Bic")
                                        .HasColumnType("text")
                                        .HasColumnName("bic");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("currency");

                                    b2.Property<string>("Iban")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("iban");

                                    b2.HasKey("PartnerBankAccountPartnerId", "PartnerBankAccountId");

                                    b2.ToTable("partner_bank_accounts");

                                    b2.WithOwner()
                                        .HasForeignKey("PartnerBankAccountPartnerId", "PartnerBankAccountId")
                                        .HasConstraintName("fk_partner_bank_accounts_partner_bank_accounts_partner_id_id");
                                });

                            b1.Navigation("BankAccount")
                                .IsRequired();

                            b1.Navigation("Partner");
                        });

                    b.OwnsOne("Ogma.Infrastructure.Persistence.Partners.ValueObjectRecords.AddressRecord", "HQAddress", b1 =>
                        {
                            b1.Property<long>("PartnerId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Apartment")
                                .HasColumnType("text");

                            b1.Property<string>("Building")
                                .HasColumnType("text");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Floor")
                                .HasColumnType("text");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Staircase")
                                .HasColumnType("text");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("PartnerId");

                            b1.ToTable("partners");

                            b1.ToJson("hq_address");

                            b1.WithOwner()
                                .HasForeignKey("PartnerId")
                                .HasConstraintName("fk_partners_partners_id");
                        });

                    b.Navigation("BankAccounts");

                    b.Navigation("HQAddress");
                });

            modelBuilder.Entity("Ogma.Infrastructure.Persistence.Partners.Models.PartnerContact", b =>
                {
                    b.HasOne("Ogma.Infrastructure.Persistence.Partners.Models.Partner", "Partner")
                        .WithMany("Contacts")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_partner_contact_partners_partner_id");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("Ogma.Infrastructure.Persistence.Partners.Models.PartnerIdentifier", b =>
                {
                    b.HasOne("Ogma.Infrastructure.Persistence.Partners.Models.Partner", "Partner")
                        .WithMany("Identifiers")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_partner_identifier_partners_partner_id");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("PartnerPartnerRoleType", b =>
                {
                    b.HasOne("Ogma.Infrastructure.Persistence.Partners.Models.Partner", null)
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_partner_roles_partners_partner_id");

                    b.HasOne("Ogma.Infrastructure.Persistence.Partners.Models.PartnerRoleType", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_partner_roles_partner_role_types_roles_id");
                });

            modelBuilder.Entity("Ogma.Infrastructure.Persistence.Partners.Models.Partner", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Identifiers");
                });
#pragma warning restore 612, 618
        }
    }
}
