// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ogma.Infrastructure.Persistence.Orders.Contexts;

#nullable disable

namespace Ogma.Infrastructure.Persistence.Orders.Migrations
{
    [DbContext(typeof(OrdersDbContext))]
    [Migration("20260106175534_CreateOrders")]
    partial class CreateOrders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("Relational:MigrationHistoryTable", "__OrdersMigrationsHistory");

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ogma.Infrastructure.Persistence.Orders.Models.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AdditionalInformation")
                        .HasColumnType("text")
                        .HasColumnName("additional_information");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("order_date");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("order_number");

                    b.Property<long>("OrderStatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_status_id");

                    b.Property<long>("OrderTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_type_id");

                    b.Property<long>("PartnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("partner_id");

                    b.Property<string>("PartnerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("partner_name");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("OrderStatusId")
                        .HasDatabaseName("ix_orders_order_status_id");

                    b.HasIndex("OrderTypeId")
                        .HasDatabaseName("ix_orders_order_type_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Ogma.Infrastructure.Persistence.Orders.Models.OrderLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AdditionalInformation")
                        .HasColumnType("text")
                        .HasColumnName("additional_information");

                    b.Property<decimal>("CancelledQuantity")
                        .HasColumnType("numeric")
                        .HasColumnName("cancelled_quantity");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("numeric")
                        .HasColumnName("exchange_rate");

                    b.Property<string>("ExchangeTargetCurrency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("exchange_target_currency");

                    b.Property<decimal>("FullfilledQuantity")
                        .HasColumnType("numeric")
                        .HasColumnName("fullfilled_quantity");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_code");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("item_id");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_name");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<decimal>("OrderedQuantity")
                        .HasColumnType("numeric")
                        .HasColumnName("ordered_quantity");

                    b.Property<decimal>("PriceAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("price_amount");

                    b.Property<string>("PriceCurrency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("price_currency");

                    b.HasKey("Id")
                        .HasName("pk_order_line");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_line_order_id");

                    b.ToTable("order_line", (string)null);
                });

            modelBuilder.Entity("Ogma.Infrastructure.Persistence.Orders.Models.OrderStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_order_statuses");

                    b.ToTable("order_statuses", (string)null);
                });

            modelBuilder.Entity("Ogma.Infrastructure.Persistence.Orders.Models.OrderType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_order_types");

                    b.ToTable("order_types", (string)null);
                });

            modelBuilder.Entity("Ogma.Infrastructure.Persistence.Orders.Models.Order", b =>
                {
                    b.HasOne("Ogma.Infrastructure.Persistence.Orders.Models.OrderStatus", "OrderStatus")
                        .WithMany()
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_orders_order_statuses_order_status_id");

                    b.HasOne("Ogma.Infrastructure.Persistence.Orders.Models.OrderType", "OrderType")
                        .WithMany()
                        .HasForeignKey("OrderTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_orders_order_types_order_type_id");

                    b.Navigation("OrderStatus");

                    b.Navigation("OrderType");
                });

            modelBuilder.Entity("Ogma.Infrastructure.Persistence.Orders.Models.OrderLine", b =>
                {
                    b.HasOne("Ogma.Infrastructure.Persistence.Orders.Models.Order", "Order")
                        .WithMany("OrderLines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_line_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Ogma.Infrastructure.Persistence.Orders.Models.Order", b =>
                {
                    b.Navigation("OrderLines");
                });
#pragma warning restore 612, 618
        }
    }
}
