// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ogma.Infrastructure.Persistence.Orders.Contexts;

#nullable disable

namespace Ogma.Infrastructure.Persistence.Orders.Migrations
{
    [DbContext(typeof(OrdersDbContext))]
    partial class OrdersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("Relational:MigrationHistoryTable", "__OrdersMigrationsHistory");

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ogma.Infrastructure.Persistence.Orders.Models.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AdditionalInformation")
                        .HasColumnType("text")
                        .HasColumnName("additional_information");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("order_date");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("order_number");

                    b.Property<long>("OrderStatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_status_id");

                    b.Property<long>("OrderTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_type_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("OrderStatusId")
                        .HasDatabaseName("ix_orders_order_status_id");

                    b.HasIndex("OrderTypeId")
                        .HasDatabaseName("ix_orders_order_type_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Ogma.Infrastructure.Persistence.Orders.Models.OrderStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_order_statuses");

                    b.ToTable("order_statuses", (string)null);
                });

            modelBuilder.Entity("Ogma.Infrastructure.Persistence.Orders.Models.OrderType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_order_types");

                    b.ToTable("order_types", (string)null);
                });

            modelBuilder.Entity("Ogma.Infrastructure.Persistence.Orders.Models.Order", b =>
                {
                    b.HasOne("Ogma.Infrastructure.Persistence.Orders.Models.OrderStatus", "OrderStatus")
                        .WithMany()
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_orders_order_statuses_order_status_id");

                    b.HasOne("Ogma.Infrastructure.Persistence.Orders.Models.OrderType", "OrderType")
                        .WithMany()
                        .HasForeignKey("OrderTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_orders_order_types_order_type_id");

                    b.OwnsMany("Ogma.Infrastructure.Persistence.Orders.Models.OrderLine", "OrderLines", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<long>("Id"));

                            b1.Property<string>("AdditionalInformation")
                                .HasColumnType("text")
                                .HasColumnName("additional_information");

                            b1.Property<decimal>("CancelledQuantity")
                                .HasColumnType("numeric")
                                .HasColumnName("cancelled_quantity");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<decimal>("ExchangeRate")
                                .HasColumnType("numeric")
                                .HasColumnName("exchange_rate");

                            b1.Property<string>("ExchangeTargetCurrency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("exchange_target_currency");

                            b1.Property<decimal>("FullfilledQuantity")
                                .HasColumnType("numeric")
                                .HasColumnName("fullfilled_quantity");

                            b1.Property<long>("OrderId")
                                .HasColumnType("bigint")
                                .HasColumnName("order_id");

                            b1.Property<decimal>("OrderedQuantity")
                                .HasColumnType("numeric")
                                .HasColumnName("ordered_quantity");

                            b1.Property<decimal>("PriceAmount")
                                .HasColumnType("numeric")
                                .HasColumnName("price_amount");

                            b1.Property<string>("PriceCurrency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("price_currency");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.Property<int>("Version")
                                .HasColumnType("integer")
                                .HasColumnName("version");

                            b1.HasKey("Id")
                                .HasName("pk_order_lines");

                            b1.HasIndex("OrderId")
                                .HasDatabaseName("ix_order_lines_order_id");

                            b1.ToTable("order_lines", (string)null);

                            b1.WithOwner("Order")
                                .HasForeignKey("OrderId")
                                .HasConstraintName("fk_order_lines_orders_order_id");

                            b1.OwnsOne("Ogma.Infrastructure.Persistence.Orders.ValueObjectRecords.OrderItem", "OrderItem", b2 =>
                                {
                                    b2.Property<long>("OrderLineId")
                                        .HasColumnType("bigint")
                                        .HasColumnName("id");

                                    b2.Property<string>("ItemCode")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("item_code");

                                    b2.Property<long>("ItemId")
                                        .HasColumnType("bigint")
                                        .HasColumnName("item_id");

                                    b2.Property<string>("ItemName")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("item_name");

                                    b2.HasKey("OrderLineId");

                                    b2.ToTable("order_lines");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderLineId")
                                        .HasConstraintName("fk_order_lines_order_lines_id");
                                });

                            b1.Navigation("Order");

                            b1.Navigation("OrderItem")
                                .IsRequired();
                        });

                    b.OwnsOne("Ogma.Infrastructure.Persistence.Orders.ValueObjectRecords.OrderPartner", "OrderPartner", b1 =>
                        {
                            b1.Property<long>("OrderId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<long>("PartnerId")
                                .HasColumnType("bigint")
                                .HasColumnName("partner_id");

                            b1.Property<string>("PartnerName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("partner_name");

                            b1.HasKey("OrderId");

                            b1.ToTable("orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId")
                                .HasConstraintName("fk_orders_orders_id");
                        });

                    b.Navigation("OrderLines");

                    b.Navigation("OrderPartner")
                        .IsRequired();

                    b.Navigation("OrderStatus");

                    b.Navigation("OrderType");
                });
#pragma warning restore 612, 618
        }
    }
}
